package io.project.fastwork.util;

import io.project.fastwork.domains.Users;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;

import java.util.stream.Stream;

public class UserArgumentProviders {
    static public class UsersArgumentsInvalidProvider implements ArgumentsProvider {
        @Override
        public Stream<? extends Arguments> provideArguments(ExtensionContext context) {
            return Stream.of(
                    Arguments.of(Users.builder().userLogin("Logi")
                            .userName("NameT")
                            .userSoname("Sonam")
                            .userPassword("Oliver23!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("123123123123")
                            .userName("NameT")
                            .userSoname("Sonam")
                            .userPassword("Oliver23!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("Name")
                            .userSoname("Sonam")
                            .userPassword("Oliver23!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("123123123")
                            .userSoname("Sonam")
                            .userPassword("Oliver23!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("NameT")
                            .userSoname("Sona")
                            .userPassword("Oliver23!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("NameT")
                            .userSoname("123123123")
                            .userPassword("Oliver23!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("NameT")
                            .userSoname("Sonam")
                            .userPassword("Oliver23")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("Name")
                            .userSoname("Sonam")
                            .userPassword("Oliver23!")
                            .userEmail("test@gmail.z")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("Name")
                            .userSoname("Sonam")
                            .userPassword("123123123")
                            .userEmail("test@gmail.z")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("Name")
                            .userSoname("Sonam")
                            .userPassword("Oliver!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("Name")
                            .userSoname("Sonam")
                            .userPassword("oliver23!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("Name")
                            .userSoname("Sonam")
                            .userPassword("Oliver23!")
                            .userEmail("123@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("Name")
                            .userSoname("Sonam")
                            .userPassword("Oliver23!")
                            .userEmail("123123123123")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("Name")
                            .userSoname("Sonam")
                            .userPassword("Oliver23!")
                            .userEmail("testgmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("NameTestNameTestNameTestNameTestNameTes")
                            .userSoname("Sona")
                            .userPassword("Oliver23!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("NameTestNameTestNameTestNameTestNameTestNameTestNameTestNameTest")
                            .userSoname("Sonam")
                            .userPassword("Oliver23!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("NameT")
                            .userSoname("SonameTestSonameTestSonameTestSonameTestSonameTest")
                            .userPassword("ZinesHosa1dasingadadwadqda123!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12Logins12Logins12Logins12Logins12Logins12")
                            .userName("NameT")
                            .userSoname("SonameTe")
                            .userPassword("ZinesHosa1dasingadadwadqda123!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Login12")
                            .userName("NameT")
                            .userSoname("SonameTe")
                            .userPassword("ZinesHosa1dasingadadwadqaasdada123!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Login12")
                            .userName("NameT")
                            .userSoname("SonameTe")
                            .userPassword("ZinesHosa1dasingadadwadqaasdada123!")
                            .userEmail("test@gmail.zasasdasd")
                            .build())
            );
        }
    }
    static public class UsersArgumentsValidProvider implements ArgumentsProvider {
        @Override
        public Stream<? extends Arguments> provideArguments(ExtensionContext context) {
            return Stream.of(
                    Arguments.of(Users.builder().userLogin("Logins12")
                            .userName("NameT")
                            .userSoname("Sonam")
                            .userPassword("Oliver23!")
                            .userEmail("test@gmail.zas")
                            .build()),
                    Arguments.of(Users.builder().userLogin("JHaris12")
                            .userName("Harris")
                            .userSoname("Jonotan")
                            .userPassword("Horiaza@21as")
                            .userEmail("jayhar@gmail.com")
                            .build()),
                    Arguments.of(Users.builder().userLogin("JHaris12")
                            .userName("Monica")
                            .userSoname("Caysea")
                            .userPassword("QwErTy132!z")
                            .userEmail("monim@gmail.com")
                            .build()),
                    Arguments.of(Users.builder().userLogin("Logins12Logins12Logins1234567")
                            .userName("NameTestNameTestNameTestNameTestNameTes")
                            .userSoname("SonameTestSonameTestSonameTestSonameTe")
                            .userPassword("ZinesHosa1dasingadadwadqda123!")
                            .userEmail("test@gmail.zas")
                            .build())
            );
        }
    }
}
