name: Build test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  run-test:
    runs-on: ubuntu-latest
    container:
      image: 'postgres:9.6.18-alpine'  
    steps:
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@1.0.11
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:  ${{ secrets.CODECOV_TOKEN }}
  
     
